server {
    listen 80;

    # Use Docker's internal DNS resolver
    resolver 127.0.0.11 valid=30s;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/owners-service/ {
        set $owners_backend http://owners-api:8080;
        
        rewrite ^/api/owners-service/(.*) /$1 break;
        proxy_pass $owners_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/pets-service/ {
        set $pets_backend http://pets-api:8080;
        
        rewrite ^/api/pets-service/(.*) /$1 break;
        proxy_pass $pets_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/vets-service/ {
        set $vets_backend http://vets-api:8080;
        
        rewrite ^/api/vets-service/(.*) /$1 break;
        proxy_pass $vets_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/visits-service/ {
        set $visits_backend http://visits-api:8080;
        
        rewrite ^/api/visits-service/(.*) /$1 break;
        proxy_pass $visits_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}